on:
  pull_request_review_comment:
    types: [created]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Set environment variables
    - name: Run Python code
      run: python my_script.py
