on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test if the action works
    steps:
      - uses: actions/checkout@v3
      - id: diff
        run: |
          diff=$(python3 diff.py main)
          echo "DIFF=$(echo $diff)" >> $GITHUB_ENV
      - id: review
        uses: samjhill/GPTReview@main
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
          REPOSITORY_NAME: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          DIFF: ${{ env.DIFF }}
